# -*- mode: conf; -*-

top-title: 临高启明

author:
  name: lingaoqiming
  email: lingaoqiming2104@sina.com
  github: lingaoqiming

markdown: kramdown
permalink: none
baseurl: /lingaoqiming.github.com
url: https://aeieli.github.io
production_url: https://aeieli.github.io/lingaoqiming.github.com/
img_url: https://aeieli.github.io/lingaoqiming.github.com/images

collections:
  characters:
    output: true
